# Generated by Django 4.2.27 on 2026-01-21 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='restaurant_menu/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of menu pages')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
