# Generated by Django 4.2.27 on 2026-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_booktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
