# Generated by Django 4.2.27 on 2026-02-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='wallet balance')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('icon_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('cashback_add', 'Cashback Add'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tin', models.CharField(max_length=20, unique=True, verbose_name='tax identification number (TIN)')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='description')),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='cashback percentage')),
                ('tags', models.ManyToManyField(blank=True, related_name='restaurants', to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='RedeemedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=100, unique=True)),
                ('receipt_number', models.CharField(max_length=50)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_receipts', to='api.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
