# Generated by Django 4.2.27 on 2026-02-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='location link'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_menus/', verbose_name='menu'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_media/', verbose_name='image')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.restaurant')),
            ],
        ),
    ]
