# Generated by Django 4.2.27 on 2026-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurant_location_link_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact number'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='working_days_and_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='working days and hours'),
        ),
    ]
