# Generated by Django 4.2.27 on 2026-03-04 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_description_en',
            field=models.TextField(blank=True, verbose_name='location description (EN)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_description_ru',
            field=models.TextField(blank=True, verbose_name='location description (RU)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_description_uz',
            field=models.TextField(blank=True, verbose_name='location description (UZ)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating (1-5)'),
        ),
    ]
