# Generated by Django 4.2.27 on 2026-03-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_restaurant_location_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_menus/', verbose_name='menu image')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='api.restaurant')),
            ],
        ),
    ]
