# Generated by Django 4.2.27 on 2026-03-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurantmenuimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
    ]
