# Generated by Django 4.2.27 on 2026-03-04 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Card number must be exactly 16 digits.', regex='^\\d{16}$')], verbose_name='card number'),
        ),
    ]
