# Generated by Django 4.2.27 on 2026-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp_restaurantadmin'),
    ]

    # Force this to run before allauth's data migration which requires the email field
    # We target both initial and the specific failing migration for maximum robustness
    run_before = [
        ('account', '0001_initial'),
        ('account', '0006_emailaddress_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
