# Generated by Django 4.2.27 on 2026-02-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp_restaurantadmin'),
    ]

    # Fields already included in 0001_initial (squashed).
    operations = []
